name: Google Service Setup
description: Sets up the google-services.json based on the flavor

runs:
  using: composite
  steps:
    - name: Create google-services.json for flavor $FLAVOR
      shell: bash
      run: |
        mkdir -p android/app/src/$FLAVOR
        echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 --decode > android/app/src/$FLAVOR/google-services.json