name: Keystore Setup
description: Sets up the keystore for signing the apk

runs:
  using: composite
  steps:
    # Decode the base64 keystore and save it as a file
    - name: Decode and save keystore
      shell: bash
      run: |
        mkdir -p android/app
        echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/app/release.jks

    # Create keystore.properties
    - name: Create keystore.properties
      shell: bash
      run: |
        echo "STORE_FILE=release.jks" >> $GITHUB_ENV